[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.88.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[plugins.inputs]

	baseUrl = "https://recipefav.netlify.app"
	sitemapPath = "/sitemap.xml"
	providers = [
		"google",
		"bing",
		"yandex"
	]